### ISSUE TITLE
zig build apk error

### ISSUE THREAD

**Issue by andodeki** [tuket/bare_apk_zig#1]
On a MacBookPro11,1
i changed the config
// const jdk_path = "C:/Program Files/Java/jdk-20";
const jdk_path = "/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home";
// const androidSdk_rootPath = "C:/Android";
const androidSdk_rootPath = "/Users/aok/.android";

// const libC_rootPath = try std.fmt.allocPrint(b.allocator, "{s}/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr", .{ndk_path});
    const libC_rootPath = try std.fmt.allocPrint(b.allocator, "{s}/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr", .{ndk_path});
 
$ zig build keystore

$ zig build apk
zig build-lib test Debug arm-linux-android: error: the following command failed with 2 compilation errors:
/usr/local/bin/zig build-lib /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/src/main.zig -llog -landroid -lc -fstrip --libc /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache/o/8446ac6de27122ce88fc2a5032dc94ce/android_libc.conf --cache-dir /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache --global-cache-dir /Users/aok/.cache/zig --name test -dynamic -target arm-linux-android -mcpu baseline -L /Users/aok/.android/ndk/25.0.8775105/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/arm-linux-androideabi/21 -fPIC --listen=- 
Build Summary: 2/10 steps succeeded; 1 failed (disable with --summary none)
apk transitive failure
└─ install generated to test.apk transitive failure
   ├─ WriteFile test.apk transitive failure
   │  └─ run /Users/aok/.android/build-tools/33.0.0/zipalign (test.aligned.apk) transitive failure
   │     └─ run /Users/aok/.android/build-tools/33.0.0/aapt (test.unaligned.apk) transitive failure
   │        └─ WriteFile lib/armeabi-v7a/libtest.so transitive failure
   │           └─ zig build-lib test Debug arm-linux-android 2 errors
   └─ run /Users/aok/.android/build-tools/33.0.0/apksigner.sh transitive failure
      └─ WriteFile test.apk (+1 more reused dependencies)
error: ld.lld: relocation R_ARM_TLS_LE32 against debug.panic_stage cannot be used with -shared
    note: defined in /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache/o/4683eceb073d710f34ca31daa15ddd6c/libtest.so.o
    note: referenced by test
    note:               /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache/o/4683eceb073d710f34ca31daa15ddd6c/libtest.so.o:(debug.panicImpl)
error: ld.lld: relocation R_ARM_TLS_LE32 against Thread.LinuxThreadImpl.tls_thread_id cannot be used with -shared
    note: defined in /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache/o/4683eceb073d710f34ca31daa15ddd6c/libtest.so.o
    note: referenced by test
    note:               /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache/o/4683eceb073d710f34ca31daa15ddd6c/libtest.so.o:(Thread.LinuxThreadImpl.getCurrentId)

**Comment by tuket** [comment]
Hi, thanks for taking the time to write the bug report.

I'm not very experienced in this kind of compiler/linker things.

However, from what I've researched, I believe there is something that could fix it. Could you try it for me please?

In build.zig, line 525, add the following line:

```diff
    step_sharedLib.force_pic = true;
+   step_sharedLib.pie = true;
    step_sharedLib.strip = true;
```

**Comment by andodeki** [comment]
hi @tuket i have added the line but still the same error

**Comment by tuket** [comment]
Hi @andodeki,
Thanks for trying that for me.
I'm not sure what might be the issue then. Are you using macos? I don't have macos to try it myself.
I have just uploaded some fixes for Linux.

**Comment by tuket** [comment]
Ah, never mind. I can repro in Windows too. Using the latest Zig master version.
I believe it's a regression of the Zig compiler as the error doesn't occur in 0.11.0. ([related](https://github.com/ziglang/zig/issues/17396))

**Comment by tuket** [comment]
Ah, another interesting thing I found: if you add the `-Drelease` flag to the zig cmd, the error disappears.

**Comment by andodeki** [comment]
> Hi @andodeki, Thanks for trying that for me. I'm not sure what might be the issue then. Are you using macos? I don't have macos to try it myself. I have just uploaded some fixes for Linux.

Yeah am using macos

**Comment by andodeki** [comment]
> Ah, another interesting thing I found: if you add the `-Drelease` flag to the zig cmd, the error disappears.

yeah a different error with `-Drelease`
```run /Users/aok/.android/build-tools/33.0.0/aapt (test.unaligned.apk): error: asset W 10-19 17:54:38  1032  8140] Asset path /Users/aok/.android/platforms/android-21/android.jar is neither a directory nor file (type=1).
ERROR: Asset package include '/Users/aok/.android/platforms/android-21/android.jar' not found.```

**Comment by tuket** [comment]
It was a bug in the zig compiler. It has now been fixed: https://github.com/ziglang/zig/issues/17575

**Comment by tuket** [comment]
It was a bug in the Zig compiler. It has now been fixed: https://github.com/ziglang/zig/issues/17575

**Comment by andodeki** [comment]
I am on MacBook
i have update the zig version to 0.12.0-dev.1139+4d106076c
i now get a different error
```
zig build-lib test Debug arm-linux-android: error: the following command failed with 2 compilation errors:
/usr/local/bin/zig build-lib /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/src/main.zig -llog -landroid -lc -fstrip --libc /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache/o/d5f58aa175fba6c7fc2a279035cabbe6/android_libc.conf --cache-dir /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache --global-cache-dir /Users/aok/.cache/zig --name test -dynamic -target arm-linux-android -mcpu baseline -L /Users/aok/.android/ndk/25.0.8775105/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/arm-linux-androideabi/21 -fPIC -fPIE --listen=- 
Build Summary: 2/10 steps succeeded; 1 failed (disable with --summary none)
apk transitive failure
└─ install generated to test.apk transitive failure
   ├─ WriteFile test.apk transitive failure
   │  └─ run /Users/aok/.android/build-tools/33.0.0/zipalign (test.aligned.apk) transitive failure
   │     └─ run /Users/aok/.android/build-tools/33.0.0/aapt (test.unaligned.apk) transitive failure
   │        └─ WriteFile lib/armeabi-v7a/libtest.so transitive failure
   │           └─ zig build-lib test Debug arm-linux-android 2 errors
   └─ run /Users/aok/.android/build-tools/33.0.0/apksigner.sh transitive failure
      └─ WriteFile test.apk (+1 more reused dependencies)
error: ld.lld: relocation R_ARM_TLS_LE32 against debug.panic_stage cannot be used with -shared
    note: defined in /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache/o/bf583deaad123b66c3c6c6d8fb6ecc51/libtest.so.o
    note: referenced by test
    note:               /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache/o/bf583deaad123b66c3c6c6d8fb6ecc51/libtest.so.o:(debug.panicImpl)
error: ld.lld: relocation R_ARM_TLS_LE32 against Thread.LinuxThreadImpl.tls_thread_id cannot be used with -shared
    note: defined in /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache/o/bf583deaad123b66c3c6c6d8fb6ecc51/libtest.so.o
    note: referenced by test
    note:               /Users/aok/Projects/rustdev/dev_work/zigdev/bare_apk_zig/zig-cache/o/bf583deaad123b66c3c6c6d8fb6ecc51/libtest.so.o:(Thread.LinuxThreadImpl.getCurrentId)
```
